import Head from 'next/head'
import HomeLayout from './HomeLayout'
import Search from '../components/Search/Search'
import Steps from '../components/Steps/Steps'
import Sidebar from '../components/Sidebar/Sidebar'
import Categories from '../components/Categories/Categories'
import Help from '../components/Help/Help'
import Alphabets from '../components/Alphabets/Alphabets'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tablet Ki</title>
        <meta name='keywords' content='tabletki' />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://tabletki.ua/images/common/32x32.png" />
      </Head>

      <HomeLayout>
        <div className=''>
          <div className='hidden justify-center items-center py-12 bg-primaryColor md:flex'>
            <h3 className='text-white text-2xl font-medium text-center'>Book products in pharmacies, save up to 30%</h3>
          </div>
          <Search />
          <Steps />
          <div className='flex justify-between px-4 py-14 w-[100%] lg:gap-8'>
            <Sidebar />
            <Categories />
          </div>
          <Help />
          <Alphabets />
        </div>
      </HomeLayout>
    </div>
  )
}
